version: '3'

services:
  postgres:
    image: 'postgres:16.1'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=postgres

  app:
    build: .
    depends_on:
      - 'postgres'
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - '3000:3000'
    volumes:
      - '.:/cine4you-api'
      - 'box:/box'

volumes:
  postgres:
  box:
